-- =============================================================================
-- AppAlter: MODULE 12 — Add AI Features & Core Difference
-- Migration: 0012_add_ai_features.sql
-- Description: Adds JSONB ai_features column to softwares for flexible SEO metadata
--              and adds core_difference and is_indexable to alternatives for VS pages.
-- =============================================================================

-- 1. Add ai_features to softwares
ALTER TABLE public.softwares 
  ADD COLUMN IF NOT EXISTS ai_features JSONB DEFAULT '{}'::jsonb;

COMMENT ON COLUMN public.softwares.ai_features IS 'Flexible UX/SEO data generated by AI (pros, cons, tldr, pricing_model_type, etc).';

-- 2. Add core_difference to alternatives
ALTER TABLE public.alternatives 
  ADD COLUMN IF NOT EXISTS core_difference TEXT;

COMMENT ON COLUMN public.alternatives.core_difference IS 'A 1-sentence punchy comparison between the software and its alternative for VS pages.';

-- 3. Add is_indexable to alternatives
ALTER TABLE public.alternatives 
  ADD COLUMN IF NOT EXISTS is_indexable BOOLEAN NOT NULL DEFAULT false;

COMMENT ON COLUMN public.alternatives.is_indexable IS 'SEO flag to determine if this alternative relationship should be indexed in sitemaps.';
