-- =============================================================================
-- AppAlter: MODULE 15 — Add ai_features to software_translations
-- Migration: 0015_add_ai_features_to_translations.sql
-- Description: Enables AI translations (pros, cons, tldr) for non-English locales
-- =============================================================================

ALTER TABLE public.software_translations 
  ADD COLUMN IF NOT EXISTS ai_features JSONB DEFAULT '{}'::jsonb;

COMMENT ON COLUMN public.software_translations.ai_features IS 'Translated flexible UX/SEO data generated by AI (pros, cons, tldr).';
